spritesheet:
  name: sproutlands
  px_total: 64
  py_total: 64
  px: 16
  py: 16
  nx: 5
  ny: 5
sprites:
  - name: down_idle
    frames:
      - [1, 0]
      - [2, 0]
  - name: down_walk_cycle
    frames:
      - [3, 0]
      - [4, 0]
  - name: up_idle
    frames:
      - [0, 1]
      - [1, 1]
  - name: up_walk_cycle
    frames:
      - [2, 1]
      - [3, 1]
  - name: left_idle
    frames:
      - [0, 2]
      - [1, 2]
  - name: left_walk_cycle
    frames:
      - [2, 2]
      - [3, 2]
  - name: right_idle
    frames:
      - [0, 3]
      - [1, 3]
  - name: right_walk_cycle
    frames:
      - [2, 3]
      - [3, 3]
