name: game_defence

on:
  push:
    branches: ["*"]

jobs:
  build-game:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-24.04, macos-14]
        include:
          - os: windows-2022
            vcpkg-response-file: vcpkg-x64-windows.txt
            triplet: x64-windows
          - os: ubuntu-24.04
            vcpkg-response-file: vcpkg-x64-linux.txt
            triplet: x64-linux
          - os: macos-14
            vcpkg-response-file: vcpkg-arm64-osx.txt
            triplet: arm64-osx
    env:
      VCPKG_ROOT: ${{ github.workspace }}/thirdparty/vcpkg
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/thirdparty/vcpkg/installed

    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v3
        with:
          submodules: true

      # See Readme.md: Linux
      - name: install-linux-deps
        if: ${{ matrix.triplet == 'x64-linux'}}
        run: |
          sudo apt-get install curl zip unzip tar pkg-config -y
          sudo apt install autoconf libtool linux-libc-dev -y
          sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev -y
          sudo apt-get install libglew-dev libxmu-dev libxi-dev libgl-dev -y
          sudo apt install libsdl2-dev libsdl2-2.0-0 -y

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: "${{ github.workspace }}/thirdparty/vcpkg"
          vcpkgJsonGlob: "**/game_defence_tests/vcpkg.json"
          runVcpkgInstall: true

      - name: get-windows-compiler
        if: ${{ matrix.triplet == 'x64-windows' }}
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: get-linux-compiler
        if: ${{ matrix.triplet == 'x64-linux'}}
        run: |
          sudo apt-get install gcc-14 -y
          sudo apt-get install g++-14 -y
          g++-14 --version
          which g++-14

      - name: get-mac-compiler
        if: ${{ matrix.triplet == 'arm64-osx' }}
        run: |
          brew install gcc@14
          g++-14 --version
          which g++-14

      - name: configure-windows
        if: ${{ matrix.triplet == 'x64-windows' }}
        run: |
          mkdir build
          cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -S . -B build -G Ninja

      - name: configure-linux
        if: ${{ matrix.triplet == 'x64-linux' }}
        run: |
          mkdir build
          cmake --no-warn-unused-cli -DCMAKE_C_COMPILER=/usr/bin/gcc-14 -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -S . -B build -G Ninja

      - name: configure-mac
        if: ${{ matrix.triplet == 'arm64-osx' }}
        run: |
          mkdir build
          cmake --no-warn-unused-cli -DCMAKE_C_COMPILER=/usr/bin/gcc-14 -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -S . -B build -G Ninja

      - name: build-tests
        run: cmake --build build --config Release --target game_defence_tests

      - name: run-tests
        run: |
          ./build/game_defence_tests/game_defence_tests.exe | findstr -i "pass"

      - name: build-game
        run: cmake --build build --config Release --target game_defence

      - name: copy-game-assets
        run: |
          cp -r ${{ github.workspace }}/game_defence/assets ./build/game_defence/
          rm -r ./build/game_defence/CMakeFiles
          rm ./build/game_defence/*.cmake 
          rm ./build/game_defence/*.manifest

      - name: release-game
        uses: actions/upload-artifact@v3
        with:
          name: game_defence-${{ matrix.os }}
          path: ./build/game_defence
