name: game_defence Tests

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            vcpkg-response-file: vcpkg-x64-windows.txt
            triplet: x64-windows
    env:
      VCPKG_ROOT: ${{ github.workspace }}/thirdparty/vcpkg
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:

    - uses: lukka/get-cmake@latest
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Restore artifacts, or setup vcpkg for building artifacts
      uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
        vcpkgDirectory: '${{ github.workspace }}/thirdparty/vcpkg'
        vcpkgJsonGlob: "**/vcpkg.json"
        runVcpkgInstall: true

    - name: Configure
      run: |
        mkdir build
        cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -S . -B build -G Ninja
    
    - name: Build
      run: cmake --build build --config Release --target game_defence_tests --parallel 10

    - name: Test
      run: ./build/game_defence_tests/game_defence_tests.exe
