name: game_defence Tests

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            vcpkg-response-file: vcpkg-x64-windows.txt
            triplet: x64-windows
    env:
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      VCPKG_ROOT: ${{ github.workspace }}/thirdparty/vcpkg

    steps:

    - uses: lukka/get-cmake@latest
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Restore artifacts, or setup vcpkg for building artifacts
      uses: lukka/run-vcpkg@v5
      id: runvcpkg
      with:
        vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
        vcpkgDirectory: '${{ github.workspace }}/thirdparty/vcpkg'
        appendedCacheKey: ${{ hashFiles(matrix.vcpkg-response-file) }}

    - name: configure
      run: |
        mkdir build
        cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -S . -B build -G Ninja
    
    # - name: Build
    #   run: cmake --build build --config Release --target game_defence_tests --parallel 10
    # - name: Make
    #   run: cd build && make
    # - name: Tests
    #   run: ./build/game_defence_tests/game_defence_tests.exe
